"""
Estrategias de la aplicación usando patrón Strategy.
"""
from .estrategias_busqueda import EstrategiaBusqueda, EstrategiaCoincidenciaExacta, EstrategiaBusquedaDifusa, EstrategiaBusquedaCompuesta
from .estrategias_precio import EstrategiaEstimacionPrecio, EstrategiaPrecioBasico, EstrategiaPrecioPorFamilia, EstrategiaPrecioPremium
from .estrategias_respuesta import EstrategiaFormateoRespuesta, EstrategiaRespuestaEstandar, EstrategiaRespuestaDetallada, EstrategiaRespuestaCompacta
from .estrategias_sugerencia import EstrategiaSugerencia, EstrategiaSugerenciaPorSimilitud, EstrategiaSugerenciaHibrida